#TODO: Finish Windows Makefile structure writeup.

create_struct:
	# TODO: Create folder structure for Windows Self Extracting Archive

copy_files:
	# TODO: Write script to copy files needed from project directory to build directory.

composer_installation:
	# TODO: Write