/* groovylint-disable-next-line CompileStatic */
pipeline {
    agent {label 'linux'}
    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Install Composer') {
            steps {
                sh 'curl -sS https://getcomposer.org/installer -o composer-setup.php'
                sh 'mkdir composer'
                sh 'php composer-setup.php --install-dir=./composer --filename=composer'
                sh 'rm -rf composer-setup.php'
            }
        }
        stage('Clone Repository') {
            steps {
                sh 'git clone https://github.com/ooobii/wumpus-copy.git'
            }
        }
        stage('Install Composer Pkgs') {
            steps {
                sh './composer/composer install --no-cache -d ./wumpus-copy'
            }
        }
        stage('Execute Tests') {
            steps {
                sh './wumpus-copy/vendor/phpunit/phpunit/phpunit --configuration ./wumpus-copy/test/phpunit.xml'
            }
        }
        stage('Build Package') {
            steps {
                sh script:'''
                #!/bin/bash
                cd ./wumpus-copy/compile/linux
                make clean
                make
                '''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'build/**/*.deb', fingerprint: true
            junit 'build/logs/**/*.xml'
        }
    }
}
