/* groovylint-disable */
pipeline {
    agent {label 'linux'}
    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Fetch Composer & Repository') {
            parallel {
                stage('Install Composer') {
                    steps {
                        sh '''
                        curl -sS https://getcomposer.org/installer -o composer-setup.php
                        mkdir composer
                        php composer-setup.php --install-dir=./composer --filename=composer
                        rm -rf composer-setup.php
                        '''
                    }
                }
                stage('Clone Repository') {
                    steps {
                        sh 'git clone git@github.com:ooobii/wumpus-copy.git .'
                    }
                }
            }
        }
        stage('Install Composer Pkgs') {
            steps {
                sh './composer/composer install --no-cache'
            }
        }
        stage('Remove Composer') {
            steps {
                sh 'rm -rf ./composer'
            }
        }
        stage('Execute Tests') {
            steps {
                sh './vendor/phpunit/phpunit/phpunit --configuration ./test/phpunit.xml'
            }
        }
        stage('Remove Composer Packages') {
            steps {
                sh 'rm -rf ./vendor'
            }
        }
        stage('Build Package') {
            steps {
                sh 'make -C "./compile/linux" package'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'build/*.deb', fingerprint: true
            junit 'test/logs/*.xml'
        }
    }
}